---
- hosts: all
  become: true

  tasks:
    - name: Install Apache and PHP
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        # This line forces Fedora to use the classic dnf backend
        # while Ubuntu safely ignores it
        use: "{{ 'apt' if ansible_os_family == 'Debian' else 'dnf' }}"

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: "{{ apache_package }}"
        state: started
        enabled: yes
