---
- hosts: all
  become: true
  
  # This section forces Fedora to use the older dnf4 backend 
  # which avoids the 'AttributeError' crash.
  module_defaults:
    ansible.builtin.dnf:
      use_backend: dnf4

  pre_tasks:
    - name: install updates for fedora
      tags: always
      ansible.builtin.dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache on web servers
      tags: apache,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  tags: db,fedora
  become: true
  tasks:

    # Sledgehammer approach
    - name: install mariadb package on db servers
      ansible.builtin.command: dnf install -y mariadb
      args:
        creates: /usr/bin/mariadb  # This prevents it from running every time
      when: ansible_distribution == "Fedora"
