---
- hosts: all
  become: true
  
  # This section forces Fedora to use the older dnf4 backend 
  # which avoids the 'AttributeError' crash.
  module_defaults:
    ansible.builtin.dnf:
      use_backend: dnf4

  pre_tasks:
    - name: install updates for fedora
      tags: always
      ansible.builtin.dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: create user
      tags: always
      ansible.builtin.user:
        name: jean
        groups: root

    - name: add sudoers file for jean
      tags: always
      ansible.builtin.copy:
        src: sudoer_jean
        dest: /etc/sudoers.d/jean
        owner: root
        group: root
        mode: 0440

    - name: add ssh key for jean user
      tags: always
      ansible.builtin.authorized_key:
        user: jean
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIBfcLmWiOLvthnqtdv1fL64ZdVVfMooDG2FXNW4apAV test@ubuntu-ws"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache on web servers (Ubuntu)
      tags: apache,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

    # Sledgehammer approach
    - name: install apache on web servers (Fedora)
      tags: apache,,fedora
      ansible.builtin.command: dnf install -y httpd
      args:
        creates: /usr/bin/httpd  # This prevents it from running every time
      when: ansible_distribution == "Fedora"


    - name: ensure apache is running (Ubuntu)
      tags: apache,ubuntu
      ansible.builtin.service:
        name: apache2
        state: started 
      when: ansible_distribution == "Ubuntu"

    # "Sledgehammer" version to avoid crashing Python-based service or dnf modules
    - name: ensure apache is running and enabled (Fedora Manual)
      ansible.builtin.shell: "systemctl enable --now httpd"
      when: ansible_distribution == "Fedora"

#     - name: change email address for admin
#      tags: apache,fedora
#     ansible.builtin.lineinfile:
#        path: /etc/httpd/conf/httpd.conf
#        regexp: '^ServerAdmin'
#        line: ServerAdmin somebody@somewhere.net
#      when: ansible_distribution == "Fedora" 
#      register: httpd

    # "Sledgehammer" version
    - name: change email address for admin (Sledgehammer)
      tags: apache,fedora
      ansible.builtin.shell: |
        sed -i 's/^ServerAdmin.*/ServerAdmin somebody@somewhere.net/' /etc/httpd/conf/httpd.conf
      when: ansible_distribution == "Fedora"
      register: httpd

        # name: restart http (Fedora)
        # tags: apache,fedora
        # ansible.builtin.service:
        #   name: httpd
        #   state: restarted
        # when: httpd.changed
        
    - name: restart http (Fedora Sledgehammer)
      tags: apache,fedora
      ansible.builtin.shell: "systemctl restart httpd"
      when: 
        - ansible_distribution == "Fedora"
        - httpd.changed


    - name: copy html file for site
      tags: apache,ubuntu
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644 

- hosts: db_servers
  tags: db,fedora
  become: true
  tasks:

    # Sledgehammer approach
    - name: install mariadb package on db servers
      ansible.builtin.command: dnf install -y mariadb
      args:
        creates: /usr/bin/mariadb  # This prevents it from running every time
      when: ansible_distribution == "Fedora"
